# Generated by Django 4.0.2 on 2022-03-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_material_task_room_materialfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfile',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classroom.material'),
        ),
    ]
