# Generated by Django 4.0.2 on 2022-03-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_materialfile_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='classroom.room'),
        ),
    ]
