# Generated by Django 4.0.2 on 2022-04-03 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_materialfile_filename_taskfile_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomment',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.material'),
        ),
    ]
