# Generated by Django 4.0.2 on 2022-04-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_task_users_submitted_alter_taskfile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users_submitted',
        ),
    ]
