# Generated by Django 4.0.2 on 2022-04-06 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_remove_task_users_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users_submitted',
            field=models.ManyToManyField(blank=True, related_name='submitted_tasks', through='classroom.TaskSubmit', to=settings.AUTH_USER_MODEL),
        ),
    ]
