# Generated by Django 4.0.2 on 2022-04-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_room_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Clas',
        ),
    ]
