# Generated by Django 4.0.2 on 2022-04-09 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_rename_room_clas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clas',
            old_name='room_code',
            new_name='clas_code',
        ),
        migrations.RenameField(
            model_name='clas',
            old_name='room_place',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='room',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='room',
            new_name='clas',
        ),
        migrations.AlterField(
            model_name='clas',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clas',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clas_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
