# Generated by Django 4.0.2 on 2022-04-10 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_rename_room_code_clas_clas_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_task_returned',
            field=models.ManyToManyField(blank=True, related_name='returned_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
