# Generated by Django 4.0.2 on 2022-04-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_task_user_task_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas',
            name='section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
